services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - '3232:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus_storage:/prometheus'
volumes:
  grafana_storage: {}
  prometheus_storage: {}